[tox]
skipsdist = true
envlist = py39, py310, py311

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
allowlist_externals = uv
passenv = UV_*
commands =
    uv run --isolated --locked --python {envpython} pytest tests
