name: Deploy Docs On Demand

on:
  workflow_dispatch:

jobs:
  deploy-docs-on-demand:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install dependencies
        run: make install

      - name: Deploy documentation
        run: uv run --locked python deploy_docs.py
