name: Deploy Docs On Demand

on:
  workflow_dispatch:

jobs:
  deploy-docs-on-demand:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v2

      - name: Install dependencies
        run: make install

      - name: Deploy documentation
        run: rye run python deploy_docs.py
